[#ftl]
[#-- @implicitly included --]

[#function getInheritanceRelations][/#function]
[#function geAssociations][/#function]
[#function getIncludeFiles][/#function]
[#function getAnnotatedFields][/#function]
[#function simpleTypeName typeMirror][/#function]
[#function typeNames][/#function]
[#function getTargetClassName resolvedMethodDeclaration][/#function]
[#function signature methodDeclaration][/#function]