@startuml
!include format.iuml
title Data Access
class GroundVehicle
class Airplane
note bottom of Airplane
This models an airplane, a //flying//
vehicle that is **very** fast.
end note

class Vehicle
class Car
class FlyingVehicle                                        
interface Flying
class Train

Vehicle <|-- GroundVehicle
FlyingVehicle <|-- Airplane
GroundVehicle <|-- Car
Vehicle <|-- FlyingVehicle
Flying <|.. FlyingVehicle
GroundVehicle <|-- Train
@enduml
