@startuml

interface Flying
class Airplane
note bottom of Airplane
This models an airplane, a //flying//
vehicle that is **very** fast.
end note

class GroundVehicle
class Train
class Vehicle
class Car
class FlyingVehicle


    FlyingVehicle <|-- Airplane

    Vehicle <|-- GroundVehicle

    GroundVehicle <|-- Train

    GroundVehicle <|-- Car

    Vehicle <|-- FlyingVehicle

    Flying <|.. FlyingVehicle
@enduml
