@startuml

class Vehicle
class Car
class GroundVehicle
class Airplane
note bottom of Airplane
This models an airplane, a //flying//
vehicle that is **very** fast.
end note

interface Flying
class FlyingVehicle
class Train

GroundVehicle <|-- Car
Vehicle <|-- GroundVehicle
FlyingVehicle <|-- Airplane
Vehicle <|-- FlyingVehicle
GroundVehicle <|-- Train
@enduml
