@startuml
!include ./format.iuml
hide empty members
title Airport class diagram

class Airplane {
    #Tuple<Wing, Wing> wings
}

class Airport
class Flight {
    -Airport airport
    -Airplane airplane
}

interface Flying
class FlyingVehicle
class Wing

FlyingVehicle <|-- Airplane
Airplane *--> "2" Wing

Airport ..> FlyingVehicle: restricted parking\ncapabilities
Airport ..> Airplane

Flight --> Airport
Flight --> Airplane

Flying <|.. FlyingVehicle

@enduml
